# Site settings
title: San Francisco Community Model
email: fedor.baart@deltares.nl
description: "The San Francisco Bay Community model"
baseurl: ""
url: "http://openearth.github.io/sfo-community"

# Build settings
markdown: kramdown
permalink: pretty
